// ============================================================
//  AI TYCOON — Daily Standup Markdown Export
// ============================================================
//
// Converts today's work events + per-agent completion stats into
// a clean Markdown summary the user can paste into a standup,
// status update, or daily report.
//
// Output structure:
//
//   # AI Tycoon 일일 리포트 — YYYY-MM-DD
//
//   ## 한눈에
//   - 활성 에이전트: N
//   - 완료 태스크: M
//   - 진행 중: K
//
//   ## 에이전트별 작업
//   - **이름** (프로젝트, 플랫폼) — 완료 X · 진행 Y
//     - 현재 작업: ...
//
//   ## 최근 이벤트 (10건)
//   - [HH:mm] [이름] 라벨 — 텍스트
//
// Exposed as `window.aiTycoonStandup.export()` which downloads a .md file.
// Also added to the command palette as "일일 리포트 Markdown".

import { S } from "./state.js";
import { AGENT_THEMES, STATUS_META, PLATFORM_META } from "./constants.js";

function themeFor(agent) {
    const idx = (S.liveAgents || []).indexOf(agent);
    return AGENT_THEMES[(idx >= 0 ? idx : 0) % AGENT_THEMES.length];
}

function platformLabel(p) { return PLATFORM_META[p]?.label || p || "Unknown"; }

function fmtHM(ts) {
    const d = new Date(ts || Date.now());
    return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function firstLine(s, max = 80) {
    if (!s) return "";
    const cleaned = String(s).replace(/\[Pasted text[^\]]*\]/g, "").trim();
    const line = cleaned.split("\n")[0].trim();
    return line.length > max ? line.slice(0, max - 1) + "…" : line;
}

function escapeMd(s) {
    return String(s ?? "").replace(/\|/g, "\\|");
}

export function buildMarkdown(lang = "ko") {
    const now = new Date();
    const ymd = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
    const agents = S.liveAgents || [];
    const events = (S.workEvents || []).slice(0, 10);
    const totalCompleted = agents.reduce((s, a) => s + (a.completedTasks || 0), 0);
    const totalOngoing = agents.reduce((s, a) => s + (a.tasks || []).filter(t => t.status === "in_progress").length, 0);
    const totalRunning = agents.filter(a => a.isRunning).length;

    const lines = [];
    if (lang === "en") {
        lines.push(`# AI Tycoon Daily Report — ${ymd}`);
        lines.push("");
        lines.push("## At a glance");
        lines.push(`- Active agents: ${totalRunning}`);
        lines.push(`- Completed tasks: ${totalCompleted}`);
        lines.push(`- In progress: ${totalOngoing}`);
    } else {
        lines.push(`# AI Tycoon 일일 리포트 — ${ymd}`);
        lines.push("");
        lines.push("## 한눈에");
        lines.push(`- 활성 에이전트: ${totalRunning}`);
        lines.push(`- 완료 태스크: ${totalCompleted}`);
        lines.push(`- 진행 중: ${totalOngoing}`);
    }
    lines.push("");

    if (agents.length > 0) {
        lines.push(lang === "en" ? "## Per-agent activity" : "## 에이전트별 작업");
        agents.forEach(a => {
            const theme = themeFor(a);
            const inProgress = (a.tasks || []).filter(t => t.status === "in_progress").length;
            const status = STATUS_META[a.isRunning ? a.status : "offline"]?.label || a.status || "—";
            lines.push(`- **${escapeMd(theme.name)}** (${escapeMd(a.projectName || "—")}, ${escapeMd(platformLabel(a.platform))}) — ${a.completedTasks || 0} done · ${inProgress} in progress · ${escapeMd(status)}`);
            const work = a.currentWork?.prompt || a.currentTask?.subject;
            if (work) {
                const label = lang === "en" ? "now" : "현재";
                lines.push(`  - ${label}: ${escapeMd(firstLine(work, 110))}`);
            }
        });
        lines.push("");
    }

    if (events.length > 0) {
        lines.push(lang === "en" ? "## Recent events (last 10)" : "## 최근 이벤트 (최근 10건)");
        events.forEach(ev => {
            const time = fmtHM(ev.ts);
            const who = ev.agentName || "—";
            const label = ev.label || ev.type || "event";
            const text = firstLine(ev.text || "", 80);
            lines.push(`- [${time}] **${escapeMd(who)}** ${escapeMd(label)}${text ? ` — ${escapeMd(text)}` : ""}`);
        });
        lines.push("");
    }

    lines.push("---");
    lines.push(lang === "en"
        ? "_Generated by AI Tycoon — see your real-time office at the dashboard._"
        : "_AI Tycoon이 자동 생성한 리포트입니다._");

    return lines.join("\n");
}

export function downloadMarkdown() {
    const lang = window.aiTycoonI18n?.getLang?.() || "ko";
    const md = buildMarkdown(lang);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const ts = new Date().toISOString().slice(0, 10);
    a.href = url;
    a.download = `ai-tycoon-standup-${ts}.md`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { a.remove(); URL.revokeObjectURL(url); }, 250);
    try {
        const title = lang === "en" ? "Standup exported" : "스탠드업 리포트 저장됨";
        const body = lang === "en" ? `${(S.liveAgents || []).length} agents` : `${(S.liveAgents || []).length}명 포함`;
        window.aiTycoonToasts?.show?.("info", title, body);
    } catch { /* ignore */ }
    return true;
}

if (typeof window !== "undefined") {
    window.aiTycoonStandup = { build: buildMarkdown, download: downloadMarkdown };
}

// ── 메모 일괄 내보내기 ────────────────────────────────────────
// 디테일 패널에서 모은 개인 메모를 한 번에 Markdown 으로 떨궈서
// 다른 도구로 옮기거나 백업할 수 있도록.
const NOTE_KEY = "ai-tycoon-agent-notes";
function loadAllNotes() {
    try { return JSON.parse(localStorage.getItem(NOTE_KEY) || "{}") || {}; }
    catch { return {}; }
}

export function buildNotesMarkdown(lang = "ko") {
    const notes = loadAllNotes();
    const keys = Object.keys(notes);
    const now = new Date();
    const ymd = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
    const lines = [];
    if (lang === "en") {
        lines.push(`# AI Tycoon — Agent Notes (${ymd})`);
        lines.push("");
        if (keys.length === 0) {
            lines.push("_No notes saved yet._");
            return lines.join("\n");
        }
        lines.push(`_Exported ${keys.length} note${keys.length > 1 ? "s" : ""}._`);
        lines.push("");
    } else {
        lines.push(`# AI Tycoon — 에이전트 메모 (${ymd})`);
        lines.push("");
        if (keys.length === 0) {
            lines.push("_저장된 메모가 없습니다._");
            return lines.join("\n");
        }
        lines.push(`_총 ${keys.length}개의 메모를 내보냈습니다._`);
        lines.push("");
    }

    // 현재 살아있는 에이전트 중 매칭되는 게 있으면 이름·프로젝트도 함께 표기
    const agents = S.liveAgents || [];
    const BT = "`"; // 백틱을 템플릿 안에 안전하게 끼워넣기 위해 별도 변수로
    keys.forEach(key => {
        const matched = agents.find(a => String(a.sessionId || "") === key || String(a.pid || "") === key);
        let label = `${BT}${key}${BT}`;
        if (matched) {
            const theme = themeFor(matched);
            const project = matched.projectName || "—";
            label = `**${theme.name}** · ${project} (${BT}${key}${BT})`;
        }
        lines.push(`### ${label}`);
        lines.push("");
        // 본문은 그대로 (Markdown 그대로 들어가도 큰 문제 없음, 단 ``` 차단)
        const body = String(notes[key] || "").replace(/```/g, "''");
        lines.push(body);
        lines.push("");
    });

    return lines.join("\n");
}

export function downloadNotesMarkdown() {
    const lang = window.aiTycoonI18n?.getLang?.() || "ko";
    const md = buildNotesMarkdown(lang);
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const ts = new Date().toISOString().slice(0, 10);
    a.href = url;
    a.download = `ai-tycoon-notes-${ts}.md`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { a.remove(); URL.revokeObjectURL(url); }, 250);
    try {
        const count = Object.keys(loadAllNotes()).length;
        const title = lang === "en" ? "Notes exported" : "메모 저장 완료";
        const body = lang === "en" ? `${count} note${count !== 1 ? "s" : ""}` : `${count}개 메모`;
        window.aiTycoonToasts?.show?.("info", title, body);
    } catch { /* ignore */ }
    return true;
}

if (typeof window !== "undefined") {
    window.aiTycoonNotes = { build: buildNotesMarkdown, download: downloadNotesMarkdown };
}
