// Refresh the local icon subset after adding a Solar icon to the UI.
// Runtime stays offline; only this explicit maintenance command uses the API.
const fs = require("node:fs/promises");
const path = require("node:path");
async function main() {
    const root = path.resolve(__dirname, "..");
    const paths = ["index.html", ...(await fs.readdir(path.join(root, "js"))).filter(n => n.endsWith(".js")).map(n => `js/${n}`)];
    const source = (await Promise.all(paths.map(p => fs.readFile(path.join(root, p), "utf8")))).join("\n");
    const names = [...new Set([...source.matchAll(/solar:([a-z0-9-]+)/g)].map(m => m[1]))].sort();
    const collection = { prefix: "solar", width: 24, height: 24, icons: {} };
    for (let i = 0; i < names.length; i += 35) {
        const response = await fetch(`https://api.iconify.design/solar.json?icons=${names.slice(i, i + 35).join(",")}`);
        if (!response.ok) throw new Error(`Icon request failed: ${response.status}`);
        const data = await response.json();
        if (data.not_found?.length) throw new Error(`Unknown icons: ${data.not_found.join(", ")}`);
        Object.assign(collection.icons, data.icons);
        if (data.aliases) collection.aliases = { ...collection.aliases, ...data.aliases };
    }
    const code = `// Solar by 480 Design, CC BY 4.0. See THIRD_PARTY.md. Generated by scripts/vendor-icons.js.\ncustomElements.get("iconify-icon").addCollection(${JSON.stringify(collection)});\n`;
    await fs.writeFile(path.join(root, "assets/vendor/solar-icons.js"), code);
    console.log(`Bundled ${Object.keys(collection.icons).length} Solar icons.`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
